import { Inter } from "next/font/google";

import type { Metadata } from "next";
import AuthProvider from "./providers/auth";
import Footer from "@/components/footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark`}>
        <AuthProvider>
          {children}
          <div className="min-h-full relative">
            <Footer />
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
